apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-cal
spec:
  selector:
    matchLabels:
      app: heavy-cal
  replicas: 1
  template:
    metadata:
      labels:
        app: heavy-cal
    spec:
      containers:
      - name: heavy-cal
        image: k8s.gcr.io/hpa-example 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: heavy-cal-inner
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: heavy-cal