apiVersion: v1
kind: Pod
metadata:
  name: nginx-use-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: test-volume 
          mountPath: /test-volume 
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: my-pvc